### ISSUE TITLE
data-world.md question

### ISSUE THREAD

**Issue by ericdill** [Data4Democracy/read-this-first#22]
In the data-world.md file there is this line:

```
If you have a file that is larger than that, try compressing the file to get it under the 100MB limit and if that doesn't work, please contact us via a new help ticket.
```

Couple of questions.

1. Who is "us"? Data4Democracy or data.world?
2. Where should the "help ticket" be submitted?

I'll submit a PR with the changes after this is clarified.

**Comment by geckya** [comment]
"Us" in this context is data.world, and the help ticket needs to be submitted through the "Feedback" link on the data.world site.
